PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX UBERON: <http://purl.obolibrary.org/obo/UBERON_>

SELECT * WHERE {
	?s a owl:Class .
	FILTER NOT EXISTS {?s rdfs:subClassOf ?parent}
	FILTER (!isBlank(?s))
	FILTER (?s != UBERON:0001062)
}